### ISSUE TITLE
What about datetime support?

### ISSUE THREAD

**Issue by qrilka** [acowley/Frames#3] opened 2015-01-19 15:09 UTC
E.g. I do some analysis including dates using R but switching to something like Frames would be cool.
BTW do you see any good way to do plots using Frames and probably some other package from hackage?

**Comment by acowley** [comment] 2015-01-19 16:39
I have plotting examples coded up, just not in this repo yet. The dataframe tutorial provides an example of defining your own universe of column types, so date parsing is certainly possible. Do you have a favored date library with a high level parsing function (`Text -> Maybe Date`)?

**Comment by qrilka** [comment] 2015-01-19 19:03
No particular preference, the only thing that comes to my mind is `time` but it is not Text-based :(
Do you plan to publish plotting examples somewhere?

**Comment by acowley** [comment] 2015-01-19 20:11
Yes, I'll post the plotting examples shortly.

The thing about date parsing is this: we need to be able to figure out the parsing function from the type. You can `newtype` a `Date` type and give it a parsing function with a particular format string, or you could get clever and use a type-level `String` to carry the format string. The latter approach, however, doesn't obviously play well with type inference, wherein we figure out what type to use based on the actual data. The problem is that we can't explore the space of format strings, but we don't want the demand that the user provide the format string to mean there is no type inference (i.e. if the user just provides the entire row type, then everything is explicit).

Getting this right will take a bit of finesse, but I think typing this out has helped me think through it :)

**Comment by qrilka** [comment] 2015-01-19 21:55
I think I will prefer to be explicit as normally I do know what do files contain (or I could refine it after playing around with `Text`s) but that's only my preference.
And as for the libraries I was suggested to look at http://hackage.haskell.org/package/strptime and it seems good enough for me

**Comment by acowley** [comment] 2015-01-20 06:49
Well being very explicit would eliminate much of the point of `Frames`, but I think the changes I made today make having a `Date` column much easier. Take a look at the updated [custom types section of the tutorial](http://acowley.github.io/Frames/#sec-3) to see how it works now. If you `newtype` your `Date` such that you can write a `Readable` instance that uses the format string you want, you can simply add your `Date` type to the default list of column types.

If you try this, please share your code as I'd really like to see it, but might not have to time to try it out myself in the immediate future.

**Comment by acowley** [comment] 2015-03-18 03:58
Closing for now as the support for whatever date format is desired should be pretty straightforward now.

**Closed by acowley** 2015-03-18 03:58 UTC

**Comment by qrilka** [comment] 2015-03-18 06:00
Did you mean http://acowley.github.io/Frames/#sec-4 ?
And thanks :)

**Comment by acowley** [comment] 2015-03-18 06:08
Yes, exactly. I know it's not baked in, and I'd be more than happy to have an example of date parsing in a test suite or at least a demo program.
