### ISSUE TITLE
Multiple custom column types

### ISSUE THREAD

**Issue by cocreature** [acowley/Frames#27] opened 2015-05-24 22:22 UTC
I have two custom column types
```haskell
newtype NumericalAnswer = NumericalAnswer (Maybe Int) deriving (Show,Read,Eq,Ord)
newtype SkillLevel = SkillLevel (Maybe Text) deriving (Show,Read,Eq,Ord)

instance Readable NumericalAnswer where
  fromText t
    | t == "0" = return $ NumericalAnswer $ Just 0
    | t == "1" = return $ NumericalAnswer $ Just 1
    | t == "2" = return $ NumericalAnswer $ Just 2
    | t == "3" = return $ NumericalAnswer $ Just 3
    | t == "4" = return $ NumericalAnswer $ Just 4
    | t == "\"\"" || t == "Don't know" = return $ NumericalAnswer Nothing
    | otherwise = mzero

instance Readable SkillLevel where
  fromText t
    | t `elem` ["none","beginner","learning","competent","expert"] = return $ SkillLevel (Just t)
    | t == "\"\"" = return $ SkillLevel Nothing
    | otherwise = mzero
```
When I add only one of them to `MyColumns` and call
```haskell
tableTypes'
  rowGen {rowTypeName = "Answer"
         ,columnUniverse = $(colQ ''MyColumns)}
  "data/raw-anon-v1-0.csv"
```
exactly those columns I want end up being converted to the added type. However if I define
```haskell
type MyColumns =  SkillLevel ': NumericalAnswer ': CommonColumns
```
the columns that should convert to `NumericalAnswer` (and do so if I don't add SkillLevel) stay Text.
It's probably me doing something terribly wrong, but I can't quite figure out what.

**Comment by acowley** [comment] 2015-05-24 23:32
I might not get to this today. Can you put up a gist or something self-contained so I can hit the ground running when I get a bit of time?

**Comment by acowley** [comment] 2015-05-24 23:54
Oh, so, looking at the code in the `ColumnUniverse` module, I wonder if adding a derived `Typeable` instance would help you. I'm a bit surprised that the compiler didn't complain about that, though, so I clearly need to look into this.

**Comment by cocreature** [comment] 2015-05-25 08:53
Sure, this is the [code](https://gist.github.com/cocreature/0d0940e94b63c978bc41). Apart from the custom columns there is not much going on there. I used the fpcomplete survey available [here](http://download.fpcomplete.com/haskell-survey-2015-05.zip). Deriving `Typeable` didn't change anything.

**Comment by acowley** [comment] 2015-05-26 01:58
The problem is that both `NumericalAnswer` and `SkillLevel` successfully parse an empty string. What happens, then, is that some rows will be inferred as having columns of type `NumericalAnswer`, but other rows will have the empty string for those same columns, and in those rows the columns in question are inferred as having type `SkillLevel`. When we consider a prefix of all rows, we try to find the smallest type capable of representing any given column. These columns in question have been inferred as both `SkillLevel` *and* `NumericalAnswer`, so we punt to `Text` because we do not know that either `SkillLevel` or `NumericalAnswer` can subsume the other.

Okay, makes sense, but this is a nuisance as the empty string is a common textual representation of lots of data types when we want to indicate a missing value. We can see this overlap in how you've embedded the `Maybe` in your column types. What we might want is some logic that deals with that for us.

Note that if we already knew the column types (because you'd inferred them from a model data file that isn't missing any values, or you've written them out manually), then the existing parsing facilities provided by `readTableMaybe` might be enough if you took the `Maybe`s out of your column types.

But the job for inference is a bit different. We need a way to indicate that, yes, a `SkillLevel` value *could* be parsed from this `Text`, but we don't feel very strongly about it. The `Readable` class gives us a function with type `Text -> Maybe a`, but we want something more like `Text -> Maybe (Either a a)`. The idea is that we want a `parseable` function that can say, "No, this text can not be parsed" or "This text could be parsed, but is ambiguous" *or* "This text can be unambiguously parsed."

Is that worth doing? If we had that, we could think about changing `lubTypeReps` in `ColumnUniverse` to compare values of `Either TypeRep TypeRep` or something like that.

The downside to this is needing to recapitulate the `Readable` package, but it isn't very complicated and we can add instances to the types from `base` as needed.

What do you think, is it worth complicating the parsing code in this way? I think it might be, as empty strings are pretty commonly used. My testing has gone along the track of the first option wherein I provide a model data file whose columns parse unambiguously, then use the types inferred from that to parse the noisy data file with `readTableMaybe`. But perhaps that's more of a pain than dealing with these ambiguities at the point of parsing.

**Comment by acowley** [comment] 2015-05-26 03:09
Okay, I tried out the change I suggested and it looks pretty good to me. I've pushed it the [parseable](https://github.com/acowley/Frames/tree/parseable) branch. What do you think?

**Comment by acowley** [comment] 2015-05-26 16:06
I realized I didn't include how I edited the example code you provided. It was very helpful!

````haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE FlexibleInstances #-}

module FPCoColumns where

import Data.Typeable
import Data.Text
import Frames
import Data.Readable
import Control.Monad
import Frames.InCore
import Frames.ColumnTypeable
import qualified Data.Vector as V

newtype NumericalAnswer = NumericalAnswer (Maybe Int) deriving (Show,Read,Eq,Ord,Typeable)
newtype SkillLevel = SkillLevel (Maybe Text) deriving (Show,Read,Eq,Ord,Typeable)

instance Parseable NumericalAnswer where
  parse t
    | t == "0" = return $ Definitely $ NumericalAnswer $ Just 0
    | t == "1" = return $ Definitely $ NumericalAnswer $ Just 1
    | t == "2" = return $ Definitely $ NumericalAnswer $ Just 2
    | t == "3" = return $ Definitely $ NumericalAnswer $ Just 3
    | t == "4" = return $ Definitely $ NumericalAnswer $ Just 4
    | t == "\"\"" || t == "Don't know" =
      return $ Possibly $ NumericalAnswer Nothing
    | otherwise = mzero

instance Parseable SkillLevel where
  parse t
    | t `elem` ["none","beginner","learning","competent","expert"] =
        return $ Definitely $ SkillLevel (Just t)
    | t == "\"\"" = return $ Possibly $ SkillLevel Nothing
    | otherwise = mzero

type instance VectorFor NumericalAnswer = V.Vector
type instance VectorFor SkillLevel = V.Vector

type MyColumns =  SkillLevel ': NumericalAnswer ': CommonColumns
````

With that change the and `parseable` branch of `Frames`, I think the columns are typed as you had originally intended.

**Comment by cocreature** [comment] 2015-05-26 16:36
First of all, keep up the good work. You are damn quick and your responses are really good.

Just tried it and it works perfectly. I think it's worth making the change as it doesn't overly complicate stuff (especially given the default implentation for `Readable`) and it also works for more complicated cases than a `Maybe` so it might avoid that some people get stuck when `readTableMaybe` is not enough.

**Comment by acowley** [comment] 2015-05-26 22:46
Thanks! I've merged the branch into master.

**Closed by acowley** 2015-05-26 22:46 UTC
